import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.css';
import "./globals.css";
import MenuBar from "@/components/blok/sideMenuBar/MenuBar";
import HeaderWrapper from "@/components/blok/Header/HeaderWrapper";
import BootstrapClient from "@/utils/BootstrapClient";
import StyledComponentsRegistry from "./registry";
const inter = Quicksand({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <header><HeaderWrapper /></header>
          <div className="d-flex">
            <aside className="menubar"><MenuBar /></aside>
            <section className="layoutChild">{children}</section>
            <footer></footer>
          </div>
          <BootstrapClient />
        </StyledComponentsRegistry>
        {/* <Script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"></Script>
        <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"></Script> */}
      </body>

    </html>
  );
}
